# -*- coding: utf-8 -*-
"""sentiment_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XWzWSiTID-y4fjSCo-PNgEjHqma0RVbe
"""

# slide_sentiment.py

import streamlit as st
import pandas as pd
import os
os.environ["TRANSFORMERS_NO_TF"] = "1"
from transformers import pipeline
from collections import Counter
import openai

# OPTIONAL: If GPT is enabled
USE_GPT = True
if USE_GPT:
    openai.api_key = st.secrets["OPENAI_API_KEY"]

@st.cache_data
def load_news_dataset():
    # Load dataset (adapt if needed)
    return pd.read_json("News_Category_Dataset_v3.json", lines=True)[['headline', 'category']].rename(columns={"headline": "text", "category": "label"})

@st.cache_resource
def load_sentiment_model():
    # Force PyTorch framework to avoid TensorFlow / Keras dependency issues
    return pipeline(
        "sentiment-analysis",
        model="distilbert-base-uncased-finetuned-sst-2-english",
        framework="pt",
        device=-1,
    )

def summarize_sentiment(company, counts):
    pos = counts.get('POSITIVE', 0)
    neg = counts.get('NEGATIVE', 0)
    neu = counts.get('NEUTRAL', 0)
    total = pos + neg + neu

    if total == 0:
        return f"No sentiment-bearing news was found about {company.title()}."

    pos_ratio = pos / total
    neg_ratio = neg / total
    neu_ratio = neu / total

    if pos_ratio > 0.6:
        return f"Recent news about {company.title()} is strongly positive, reflecting widespread optimism."
    elif neg_ratio > 0.6:
        return f"The media coverage of {company.title()} has been largely negative, signaling concern or criticism."
    elif neu_ratio > 0.5:
        return f"Recent headlines about {company.title()} are mostly neutral, offering factual or mixed reporting."
    elif pos_ratio > neg_ratio:
        return f"Overall, the news sentiment toward {company.title()} leans positive, but includes some critical voices."
    elif neg_ratio > pos_ratio:
        return f"Overall, the news sentiment toward {company.title()} leans negative, though some optimism is present."
    else:
        return f"The media tone on {company.title()} is balanced between positive and negative viewpoints."

def gpt_enhance_summary(summary, company):
    prompt = f"""
Based on the following summary of media sentiment about {company}, write a concise and professional 2-sentence insight for a business slide.

Summary:
"{summary}"

Insight:
"""
    try:
        response = openai.chat.completions.create(
            model="gpt-4o",
            messages=[
                {"role": "system", "content": "You are a business analyst."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.7,
            max_tokens=100
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        return f"(GPT error: {e})"

def run():
    st.title("📰 Company News Sentiment Analyzer")
    st.markdown("Enter a company name to analyze news sentiment and generate a slide summary.")

    company = st.text_input("🔎 Company name", placeholder="Example: Tesla, Netflix, Microsoft")
    if not company:
        return

    news_df = load_news_dataset()
    company_news = news_df[news_df['text'].str.lower().str.contains(company.lower())]

    st.write(f"✅ Found {len(company_news)} headlines mentioning **{company.title()}**.")
    if company_news.empty:
        st.warning("No news headlines matched.")
        return

    # Run sentiment in batch
    sentiment_model = load_sentiment_model()
    with st.spinner("🔍 Analyzing sentiment..."):
        sentiments = sentiment_model(company_news['text'].tolist(), batch_size=32)
        company_news['sentiment'] = [r['label'] for r in sentiments]

    st.dataframe(company_news[['text', 'sentiment']].head(10), use_container_width=True)

    # Count sentiment types
    counts = company_news['sentiment'].value_counts().to_dict()
    st.subheader("📊 Sentiment Distribution")
    st.json(counts)

    summary = summarize_sentiment(company, counts)
    st.subheader("🧠 Logic-Based Summary")
    st.info(summary)

    # Optional: GPT-enhanced slide output
    if USE_GPT:
        with st.spinner("✨ Generating enhanced business insight..."):
            gpt_summary = gpt_enhance_summary(summary, company)
            st.subheader("📝 GPT Slide Output")
            st.success(gpt_summary)

if __name__ == "__main__":
    run()